In [53]:
import pandas as pd

In [54]:
data = pd.read_csv(r'S:\17.07.25\25712180_BEINDATANEWRPT.CSV', dtype='str')
data=data.loc[data['Contract Number']!='2098194']

In [55]:
data.loc[data['Status']=='Active','Status']='1 Active'
data.loc[data['Status']=='Suspended','Status']='2 Suspended'

data.loc[data['Status']=='DIS','Status']='3 Disconnected'

In [56]:
data1000s = data.loc[data['Item Description STB']=='beIN Decoder 1000s'].copy()
data1000s['End Date'] = pd.to_datetime(data1000s['End Date'],dayfirst=True)

In [57]:
data1000s['payment_plan'] = 'Non Installment'
data1000s.loc[data1000s['Customer Type'].str.contains('Installment'),'payment_plan'] = 'Installment'
# data1000s.loc[data1000s['Status']=='Suspended','Status']='DIS'

In [58]:
data1000s.columns

Index(['Customer Number', 'Customer Type', 'Entity', 'Contract Number',
       'Start Date', 'End Date', 'Plan', 'Status', 'Decoder',
       'Item Description STB', 'Smart Card', 'Item Description SC',
       'Next Billing Date', 'Billing Cycle', 'PPV Balance', 'Customer Balance',
       'Outstanding Balance', 'payment_plan'],
      dtype='object')

In [59]:
data1000s = data1000s.sort_values(['Status','End Date'], ascending=[True,False])
data1000s= data1000s.drop_duplicates(subset=['Decoder'], keep='first')
data1000s= data1000s.reset_index()
data1000s['month'] = data1000s['End Date'].dt.month
data1000s['year'] = data1000s['End Date'].dt.year

In [60]:
data1000s['Status'].value_counts()

Status
3 Disconnected    313197
1 Active           43411
2 Suspended         5790
Name: count, dtype: int64

In [61]:
data1000s.loc[data1000s['Decoder']=='0319620280']

,index,Customer Number,Customer Type,Entity,Contract Number,Start Date,End Date,Plan,Status,Decoder,...,Smart Card,Item Description SC,Next Billing Date,Billing Cycle,PPV Balance,Customer Balance,Outstanding Balance,payment_plan,month,year
49200,1583321,16810711,beIN Dealer,CNE Head office,1048241,01-01-2021,2021-12-31,Ultimate,2 Suspended,0319620280,...,10388726688,beIN Smartcard 1000s,01-01-2022,12M,0 Dr,0 Dr,0 DR,Non Installment,12,2021

In [65]:
data1000s.loc[data1000s['Status']=='1 Active','Status']='Active'
data1000s.loc[data1000s['Status']=='2 Suspended','Status']='Suspended'

data1000s.loc[data1000s['Status']=='3 Disconnected','Status']='Disconnected'

data1000s.to_csv('data1000s_clean.csv', index = False)

In [63]:
data.loc[data['Decoder']=='0319620280']

,Customer Number,Customer Type,Entity,Contract Number,Start Date,End Date,Plan,Status,Decoder,Item Description STB,Smart Card,Item Description SC,Next Billing Date,Billing Cycle,PPV Balance,Customer Balance,Outstanding Balance
1583313,16810711,beIN Dealer,CNE Head office,1048241,01-01-2020,31-12-2020,beIN Premium,3 Disconnected,0319620280,beIN Decoder 1000s,10388726688,beIN Smartcard 1000s,01-01-2021,12M,0 Dr,0 Dr,0 DR
1583316,16810711,beIN Dealer,CNE Head office,608121,01-01-2019,31-12-2019,beIN Premium,3 Disconnected,0319620280,beIN Decoder 1000s,10388726688,beIN Smartcard 1000s,01-01-2020,12M,0 Dr,0 Dr,0 DR
1583319,16810711,beIN Dealer,CNE Head office,2328895,01-01-2023,31-12-2023,Ultimate,3 Disconnected,0319620280,beIN Decoder 1000s,10388726688,beIN Smartcard 1000s,NaN,12M,0 Dr,0 Dr,0 DR
1583320,16810711,beIN Dealer,CNE Head office,1048241,01-01-2022,31-12-2022,Ultimate,3 Disconnected,0319620280,beIN Decoder 1000s,10388726688,beIN Smartcard 1000s,01-01-2023,12M,0 Dr,0 Dr,0 DR
1583321,16810711,beIN Dealer,CNE Head office,1048241,01-01-2021,31-12-2021,Ultimate,2 Suspended,0319620280,beIN Decoder 1000s,10388726688,beIN Smartcard 1000s,01-01-2022,12M,0 Dr,0 Dr,0 DR
1583323,16810711,beIN Dealer,CNE Head office,3477015,01-01-2025,31-12-2025,ULTIMATE 09.24,3 Disconnected,0319620280,beIN Decoder 1000s,10388726688,beIN Smartcard 1000s,NaN,12M,0 Dr,0 Dr,0 DR
1583326,16810711,beIN Dealer,CNE Head office,659408,10-06-2019,09-08-2019,Afcon-Cupa2019.684,3 Disconnected,0319620280,beIN Decoder 1000s,10388726688,beIN Smartcard 1000s,10-08-2019,2M,0 Dr,0 Dr,0 DR