In [ ]:
import pandas as pd

In [ ]:
file = pd.read_csv(r'S:\29.07.25\25995491_BEINDATANEWRPT.CSV', dtype='str')

In [ ]:
file['Plan']=file['Plan'].str.lower()

In [9]:
prem = file.loc[file['Plan'].str.contains('prem')]
prem_prods = ['premium', 'premium 09.24', 'premium act bts 2021', 'premium 2024',
       'bein premium', 'premium 2025 summer 26', 'commud-premium',
       'btl premium 25%', 'premium 2025 summer 34',
       'premium12 25% bts 2024', 'premium 2025 summer 37',
       'comdth- premium', 'premium 2025 summer 25',
       'premium12mmega 9-12m 02.25', 'premium-nc',
       'premium 2025 summer 35', 'premium 2025 summer 23',
       'premium6msupr 4-6m 02.25', 'premium6 15%? bts 2024',
       'premium 2025 summer 27', 'premium 2025 summer 8',
       'premium 2025 summer 36', 'premium 2025 summer 29',
       'premium 2025 summer 31', 'premium 2025 summer 32',
       'premium 2025 summer 38', 'premium 2024-nc',
       'premium 2025 summer 24', 'premium 2025 summer 20',
       'premium 2025 summer 4', 'premium 2025 summer 30',
       'premium 2025 summer 17', 'premium 2025 summer 40',
       'premium 2025 summer 21', 'premium 2025 summer 39',
       'premium 2025 summer 11', 'premium 2025 summer 14',
       'premium 2025 summer 12', 'premium 2025 summer 7',
       'premium 2025 summer 22', 'premium 2025 summer 18',
       'premium 2025 summer 33', 'premium 2025 summer 10',
       'premium 2025 summer 5', 'premium 2025 summer 13',
       'premium 2025 summer 19', 'ncpremium 09.24',
       'kickoff premium free', 'premium 2025 summer 1',
       'premium 2025 summer 2', 'premium 2025 summer 3',
       'premium 2025 summer 6', 'premium 2025 summer 9',
       'premium 2025 summer 15', 'premium 2025 summer 16',
       'premium 2025 summer 28', 'premium6mess frebx 02.25',
       'premium12madv frebx 02.25', 'premium24mvip frebx 02.25',
       'premium24? 50%box']

In [11]:
prem_act = file.loc[(file['Plan'].isin(prem_prods)) & (file['Status']=='Active')]

In [12]:
prem_act

,Customer Number,Customer Type,Entity,Contract Number,Start Date,End Date,Plan,Status,Decoder,Item Description STB,Smart Card,Item Description SC,Next Billing Date,Billing Cycle,PPV Balance,Customer Balance,Outstanding Balance
35,9996973,beIN Quartar Installment,CNE Head office,3512950,30-01-2025,29-01-2026,premium 09.24,Active,0294976516,CNE 3030 decoder,42771839117,Smartcard 3030,30-07-2025,3M,0 Dr,0 Dr,0 DR
39,9995200,CNE Subscriber,CNE Head office,3287170,26-08-2024,25-08-2025,premium 2024,Active,0302777333,beIN Decoder 1000s,42768381792,beIN Smartcard 1000s,26-08-2025,12M,0 Dr,0 Dr,0 DR
44,9995200,CNE Subscriber,CNE Head office,3673908,26-08-2025,25-08-2026,premium 2025 summer 26,Active,0302777333,beIN Decoder 1000s,42768381792,beIN Smartcard 1000s,26-08-2026,12M,0 Dr,0 Dr,0 DR
78,9991348,CNE Subscriber,CNE Head office,3603370,26-05-2025,25-05-2026,premium 09.24,Active,0319512059,beIN Decoder 1000s,10388413238,beIN Smartcard 1000s,26-05-2026,12M,0 Dr,0 Dr,0 DR
82,999089,Hotels,CNE Commercial Warehouse,881524,24-08-2024,23-08-2025,commud-premium,Active,0303260715,beIN Decoder 1000s,10088350235,beIN Smartcard 1000s,NaN,12M,0 Dr,0 Dr,0 DR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2707351,10015691,CNE Subscriber,Fysal 2,3334088,12-10-2024,11-10-2025,premium12 25% bts 2024,Active,0297170093,beIN Decoder 1000s,42916631676,beIN Smartcard 1000s,12-10-2025,12M,0 Dr,0 Dr,0 DR
2707362,10011116,CNE Subscriber,CNE Head office,3256892,08-08-2024,07-08-2025,premium 2024,Active,0302768705,beIN Decoder 1000s,42916637921,beIN Smartcard 1000s,08-08-2025,12M,0 Dr,1 Cr,1 CR
2707372,10006697,CNE Subscriber,CNE Head office,3275701,18-08-2024,17-08-2025,premium 2024,Active,0349904394,Humax C1 Decoder,10708980312,CNE V7 Card,18-08-2025,12M,0 Dr,0 Dr,0 DR
2707403,10000224,CNE Subscriber,Maadi,3241267,01-08-2024,31-07-2025,premium 2024,Active,0302778636,beIN Decoder 1000s,42916818737,beIN Smartcard 1000s,01-08-2025,12M,0 Dr,0 Dr,0 DR
2707405,10000116,beIN Quartar Installment,CNE Head office,3283505,24-08-2024,23-08-2025,premium 2024,Active,0302785494,beIN Decoder 1000s,42768429567,beIN Smartcard 1000s,24-08-2025,3M,0 Dr,0 Dr,0 DR

In [17]:
prem_act.groupby('Plan').agg(count=('Smart Card','count')).reset_index().to_excel('active_premium.xlsx', index=False)

In [14]:
prem_act.loc[prem_act['Plan']=='bein premium']

,Customer Number,Customer Type,Entity,Contract Number,Start Date,End Date,Plan,Status,Decoder,Item Description STB,Smart Card,Item Description SC,Next Billing Date,Billing Cycle,PPV Balance,Customer Balance,Outstanding Balance
14115,19198928,VIP_CNE,CNE Head office,3708246,01-01-2025,31-12-2025,bein premium,Active,0373088039,beIN 4k,10732870653,CNE V7 Card,NaN,12M,0 Dr,0 Dr,0 DR
14343,19198650,VIP_CNE,CNE Head office,3690124,01-01-2025,31-12-2025,bein premium,Active,0373072881,beIN 4k,10672294815,CNE V7 Card,NaN,12M,0 Dr,0 Dr,0 DR
15426,19197339,VIP_CNE,CNE Head office,3652653,01-01-2025,31-12-2025,bein premium,Active,0373053040,beIN 4k,10732940746,CNE V7 Card,NaN,12M,0 Dr,0 Dr,0 DR
15427,19197338,VIP_CNE,CNE Maintainance,3652638,01-01-2025,31-12-2025,bein premium,Active,0373089208,beIN 4k,10732769533,CNE V7 Card,NaN,12M,0 Dr,0 Dr,0 DR
15428,19197337,VIP_CNE,CNE Head office,3652637,01-01-2025,31-12-2025,bein premium,Active,0373086863,beIN 4k,10732769509,CNE V7 Card,NaN,12M,0 Dr,0 Dr,0 DR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2587731,13616467,VIP_CNE,CNE Head office,2328632,01-01-2023,31-12-2025,bein premium,Active,0373063654,beIN 4k,10732567994,CNE V7 Card,NaN,12M,0 Dr,0 Dr,0 DR
2629640,12928640,VIP_CNE,CNE Head office,1045416,01-01-2021,31-12-2021,bein premium,Active,0319192884,beIN Decoder 1000s,10137738703,beIN Smartcard 1000s,NaN,12M,0 Dr,0 Dr,0 DR
2629645,12928640,VIP_CNE,CNE Head office,2328518,01-01-2023,31-12-2025,bein premium,Active,0319192884,beIN Decoder 1000s,10137738703,beIN Smartcard 1000s,NaN,12M,0 Dr,0 Dr,0 DR
2694885,11567022,VIP_CNE,CNE Head office,1045474,01-01-2021,31-12-2021,bein premium,Active,0351819696,Humax C1 Decoder,10110539698,beIN Smartcard 1000s,NaN,12M,0 Dr,0 Dr,0 DR
2694886,11567022,VIP_CNE,CNE Head office,2328472,01-01-2023,31-12-2025,bein premium,Active,0351819696,Humax C1 Decoder,10110539698,beIN Smartcard 1000s,NaN,12M,0 Dr,0 Dr,0 DR