In [1]:
import pandas as pd

In [12]:
data_src  = pd.read_excel(r"C:\Users\mturky\Documents\axa_mistake.xlsx")

In [13]:
data = data_src.copy()

data.columns

Index(['EmpCode', 'MainInsuredCardNo', 'FIRSTNAME'], dtype='object')

In [14]:
data = data.drop_duplicates(subset=['EmpCode', 'MainInsuredCardNo'])

In [15]:
data

     EmpCode  MainInsuredCardNo                     FIRSTNAME
0         11         5110536656        MOHAMED MOHAMED KASSEM
3         22         5110536657         TAREK MOHAMED SHEHATA
7         23         5110536658     EMAN AHMED MOHAMED HEMMAT
8         24         5110536659             HATEM BAKRY AHMED
9         25         5110536660       SAYED FAWZY BADR ELDEIN
..       ...                ...                           ...
465     1010         5110536906  MAHMOUD ABDELLATIF MANZALAWY
467     2066         5110536907            NORA WAGDY MOHAMED
468     3003         5110536908       KHALED SAEED ALYMETWALY
472      258         5110536908   SEHAM ELSAID MOUSA MOHAMED
475      315         5110536908            HEBA  NASER  SEDKY

[262 rows x 3 columns]

In [16]:
grp = data.groupby('EmpCode').agg(count=('MainInsuredCardNo','count')).reset_index()

In [28]:
grp = grp.loc[grp['count']>1]
grp

     EmpCode  count
51       153      2
62       180      2
88       236      2
99       258      2
100      259      2
101      262      2
115      286      2
128      315      2
139      341      2

In [21]:
data_src.loc[data_src['EmpCode']==341]

     EmpCode  MainInsuredCardNo                  FIRSTNAME
314      341         5110536794        SELIM MOHAMED TAHER
315      341         5110536795  MOHAMED TAHER NASR ELDIEN
316      341         5110536795       ASMAA KHALAF KHALAF
317      341         5110536795        HAYAH MOHAMED TAHER

In [23]:
data_src.loc[data_src['EmpCode'].isin(grp['EmpCode'])].to_csv('mistakes.csv', index=False)

In [26]:
grp1 = data.groupby('MainInsuredCardNo').agg(count=('EmpCode','count')).reset_index()
grp1 = grp1.loc[grp1['count']>1]

In [27]:
grp1

     MainInsuredCardNo  count
50          5110536706      2
61          5110536717      2
87          5110536743      2
99          5110536755      2
100         5110536756      2
114         5110536770      2
138         5110536794      2
252         5110536908      3