In [ ]:
import pandas as pd

In [ ]:
# cols = ['Customer#', 'User Entity', 'Transaction Type',
#        'Transaction#', 'Transaction User', 'Transaction Date', 'Description']
# history1_8_src = pd.read_csv(r"C:\Users\mturky\Downloads\31007760_ALLUSERHISTDTLS.CSV", usecols=cols)
# history9_src = pd.read_csv(r"C:\Users\mturky\Downloads\31022370_ALLUSERHISTDTLS.CSV", usecols=cols)


# history = pd.concat([history1_8_src,history9_src])
# filter_types = ['RETRACK','PROVSIONCOMMAND','SENDOSD' ]
# history = history.loc[~history['Transaction Type'].isin(filter_types)]
# history['Transaction Date'] = pd.to_datetime(history['Transaction Date'], dayfirst=True)

# history.to_parquet("history_JAN_SEP_2026.parquet", index=False)

In [ ]:
history = pd.read_parquet('history_JAN_SEP_2026.parquet')

In [ ]:
history

In [ ]:
history.loc[(history['Customer#']==17331493) & (history['Transaction Date'].dt.date==pd.Timestamp( '2026-09-03').date())]

In [78]:
history_entity_mod = history.loc[(history['Transaction Type']=='Modify User Operational Entity') ].copy()
history_entity_mod['Description'] = history_entity_mod['Description'].str.replace('User Operational entity has been modified from ','')
history_entity_mod[['from','to']] = history_entity_mod['Description'].str.split(' to ', expand=True)

history_contract_disconnect = history.loc[(history['Transaction Type']=='Disconnect Contract') ].copy()

In [79]:
history_contract_disconnect

,Customer#,User Entity,Transaction Type,Transaction#,Transaction User,Transaction Date,Description
375,19196037,CNE Head office,Disconnect Contract,3600938,Ahmed Abdel Aziz Bahr,2026-10-01 13:24:20,Contract # 3600938 with Plan(s) ComDTH- Premiu...
446,19155175,CNE Head office,Disconnect Contract,3035711,Ahmed Abdel Aziz Bahr,2026-10-01 13:16:42,Contract # 3035711 with Plan(s) ComDTH- Premiu...
1293,18911784,CNE Head office,Disconnect Contract,4770420,Ahmed Mongi,2026-10-01 10:20:17,Contract # 4770420 with Plan(s) Premium 6 Mont...
2329,17639187,CNE Head office,Disconnect Contract,3331743,Super User,2026-10-01 02:20:11,Contract # 3331743 with Plan(s) PREMIUM 09.24 ...
2330,19192119,CNE Head office,Disconnect Contract,4710460,Super User,2026-10-01 02:20:10,Contract # 4710460 with Plan(s) PREMIUM 09.24 ...
...,...,...,...,...,...,...,...
5083627,19080811,CNE Head office,Disconnect Contract,2089983,Super User,2026-09-01 02:00:25,Contract # 2089983 with Plan(s) ComDTH- Premiu...
5083628,18934952,CNE Head office,Disconnect Contract,2023072,Super User,2026-09-01 02:00:25,Contract # 2023072 with Plan(s) ComDTH- Premiu...
5083629,18984957,CNE Head office,Disconnect Contract,1999532,Super User,2026-09-01 02:00:25,Contract # 1999532 with Plan(s) ComDTH- Premiu...
5083630,18871562,CNE Head office,Disconnect Contract,1593665,Super User,2026-09-01 02:00:25,Contract # 1593665 with Plan(s) ComDTH- Premiu...
5083631,19029439,CNE Head office,Disconnect Contract,1553078,Super User,2026-09-01 02:00:24,Contract # 1553078 with Plan(s) ComDTH- Premiu...

In [77]:
history_entity_mod.loc[(history_entity_mod['Transaction User']!='Super User')
                        & (history_entity_mod['from']=='CNEHO')
                        & ~(history_entity_mod['to'].str.contains('co',case=False))
                        & ~(history_entity_mod['to'].str.contains('cntr',case=False))
                        ]

,Customer#,User Entity,Transaction Type,Transaction#,Transaction User,Transaction Date,Description,from,to
4440,19255847,CNE Head office,Modify User Operational Entity,977093,Ahmed Khalaf,2026-09-30 23:56:11,CNEHO to BEINHELWAN,CNEHO,BEINHELWAN
4481,19255846,CNE Head office,Modify User Operational Entity,977092,Ahmed Khalaf,2026-09-30 23:34:52,CNEHO to EDDZHRA,CNEHO,EDDZHRA
94371,19171793,CNE Head office,Modify User Operational Entity,543825,Kholoud Tayef Ahmed,2026-09-21 12:07:54,CNEHO to BEINOCT,CNEHO,BEINOCT
209525,19219726,CNE Head office,Modify User Operational Entity,599507,Ahmed Saad,2026-09-10 08:48:38,CNEHO to BEINHELWAN,CNEHO,BEINHELWAN
209532,15753761,CNE Head office,Modify User Operational Entity,732108,Ahmed Saad,2026-09-10 08:44:42,CNEHO to BEINHELWAN,CNEHO,BEINHELWAN
...,...,...,...,...,...,...,...,...,...
4987275,19219726,CNE Head office,Modify User Operational Entity,599507,Ahmed Saad,2026-09-10 08:48:38,CNEHO to BEINHELWAN,CNEHO,BEINHELWAN
4987282,15753761,CNE Head office,Modify User Operational Entity,732108,Ahmed Saad,2026-09-10 08:44:42,CNEHO to BEINHELWAN,CNEHO,BEINHELWAN
4987284,19049144,CNE Head office,Modify User Operational Entity,350622,Ahmed Saad,2026-09-10 08:43:28,CNEHO to BEINHELWAN,CNEHO,BEINHELWAN
4987295,15951492,CNE Head office,Modify User Operational Entity,774080,Ahmed Saad,2026-09-10 08:38:20,CNEHO to BEINHELWAN,CNEHO,BEINHELWAN
4987297,15617803,CNE Head office,Modify User Operational Entity,773095,Ahmed Saad,2026-09-10 08:36:47,CNEHO to BEINHELWAN,CNEHO,BEINHELWAN