In [1]:
import pandas as pd

In [2]:
bein = pd.read_csv(r"S:\19.07.26\30577978_BEINDATANEWRPT.CSV", dtype='str')

In [3]:
result = pd.read_excel(r"C:\Users\mturky\Documents\Result.xlsx", dtype='str')

In [5]:
bein['short'] = bein['Smart Card'].astype(str).str[:10]

In [6]:
bein

,Customer Number,Customer Type,Entity,Contract Number,Start Date,End Date,Plan,Status,Decoder,Item Description STB,Smart Card,Item Description SC,Next Billing Date,Billing Cycle,PPV Balance,Customer Balance,Outstanding Balance,short
0,9999654,beIN Quartar Installment,CNE Head office,1011252,29-11-2019,28-11-2021,beIN Sports,DIS,0303293316,beIN Decoder 1000s,42916623426,beIN Smartcard 1000s,29-11-2021,3M,0 Dr,.01 Cr,.01 CR,4291662342
1,9999654,beIN Quartar Installment,CNE Head office,1929649,20-01-2022,19-01-2023,Premium,DIS,0303293316,beIN Decoder 1000s,42916623426,beIN Smartcard 1000s,20-01-2023,3M,0 Dr,.01 Cr,.01 CR,4291662342
2,9999654,beIN Quartar Installment,CNE Head office,50896,31-10-2018,30-10-2019,beIN Sports,DIS,0303293316,beIN Decoder 1000s,42916623426,beIN Smartcard 1000s,31-10-2019,3M,0 Dr,.01 Cr,.01 CR,4291662342
3,9999475,beIN Bi Installment,CNE Head office,1603175,18-08-2021,17-08-2022,Premium Act BTS 2021,DIS,0303293326,beIN Decoder 1000s,42916729918,beIN Smartcard 1000s,18-08-2022,12M,0 Dr,0 Dr,0 DR,4291672991
4,9999475,beIN Bi Installment,CNE Head office,1498705,30-05-2021,29-09-2021,EURO20-EB Add On,DIS,0303293326,beIN Decoder 1000s,42916729918,beIN Smartcard 1000s,30-09-2021,4M,0 Dr,0 Dr,0 DR,4291672991
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3038717,10000116,CNE Subscriber,Meet Ghamr,2080577,22-08-2022,21-08-2023,Premium,DIS,0302785494,beIN Decoder 1000s,42768429567,beIN Smartcard 1000s,22-08-2023,3M,0 Dr,0 Dr,0 DR,4276842956
3038718,10000116,CNE Subscriber,Meet Ghamr,2563708,22-08-2023,21-08-2024,Premium,DIS,0302785494,beIN Decoder 1000s,42768429567,beIN Smartcard 1000s,22-08-2024,3M,0 Dr,0 Dr,0 DR,4276842956
3038719,10000116,CNE Subscriber,Meet Ghamr,51041,21-08-2018,20-08-2019,beIN Sports,DIS,0302785494,beIN Decoder 1000s,42768429567,beIN Smartcard 1000s,21-08-2019,3M,0 Dr,0 Dr,0 DR,4276842956
3038720,10000116,CNE Subscriber,Meet Ghamr,1202110,22-08-2020,21-08-2021,beIN Sports,DIS,0302785494,beIN Decoder 1000s,42768429567,beIN Smartcard 1000s,22-08-2021,6M,0 Dr,0 Dr,0 DR,4276842956
3038721,10000116,CNE Subscriber,Meet Ghamr,4092109,09-03-2026,08-09-2027,PREMIUM18 Ramadan26 FWC complm.,Active,0302785494,beIN Decoder 1000s,42768429567,beIN Smartcard 1000s,09-09-2027,18M,0 Dr,0 Dr,0 DR,4276842956

In [7]:
result

     SN.          SC Product
0      1  1038914962  SUMW26
1      2  4276834403     NaN
2      3  1073278206     NaN
3      4  1073271599     NaN
4      5  1067972227     NaN
..   ...         ...     ...
166  167  1073919747     NaN
167  168  1073933426     NaN
168  169  1073933530     NaN
169  170  1073933511     NaN
170  171  1073933339     NaN

[171 rows x 3 columns]

In [9]:
pd.merge(left=result,right=bein[['Customer Number','Smart Card','short']], left_on='SC', right_on='short').to_csv('complete.csv',index=False)