In [ ]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [41]:
ft_original = pd.read_csv(r"S:\24.08.26\30798787_NEWCNEFINTRANSRPT.CSV", on_bad_lines='skip', dtype='str')

In [42]:
ft = ft_original.copy()
ft = ft.loc[ft['Doc Type']=='Invoice']

In [43]:
ft['Created Date'] = pd.to_datetime(ft['Created Date'], dayfirst=True)

C:\Users\mturky\AppData\Local\Temp\1\ipykernel_47236\4204500078.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  ft['Created Date'] = pd.to_datetime(ft['Created Date'], dayfirst=True)

In [44]:
ft = ft.loc[(ft['Created Date']>='2026-08-01') & (ft['Created Date']<='2026-08-23')]

In [45]:
ft[['Period From', 'Period To']] = ft['Bill Period'].str.split(' - ', n=1, expand=True)
ft['Period From'] = pd.to_datetime(ft['Period From'], dayfirst=True)
ft = ft.loc[(ft['Period From']>='2026-08-01')]

In [46]:
ft1 = ft.loc[~ft['Plan Name'].str.contains('afc', case=False, na=False)]

In [47]:
ft1

,Subscriber Nr,Doc Type,Ftnr,Created Date,Created Time,Doc Status,Period From,Period To,Bank Date,Amount,User Name,User Fullname,Payment Ref No,Event Description,Payment Batch No,Batch Approval No,Default Entity Type,Collecting Entity,Pay Mode,Jv Type,Book Number,Smartcard,Bill Period,Bill Cycle,Invoice Type,Plan Name,Contract Number,Channel Provider,Subscriber Type,Subscriber Entity,Last Four Digits Of Card,PAYMENT_FLAG,DS_PAYMENT_FLAG
86578,17032913,Invoice,INV_9130052,2026-08-01,12:05:22 AM,Posted,2026-08-01,31/10/2026,NaN,1522,SYSADMIN,Super User,NaN,NaN,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10739356789,01/08/2026 - 31/10/2026,3M,Subscription Invoice,PREMIUM 09.24,3515897,beIN,beIN Quartar Installment,CNE Head office,NaN,NaN,NaN
86579,14789616,Invoice,INV_9130054,2026-08-01,12:05:23 AM,Posted,2026-08-01,31/10/2026,NaN,1522,SYSADMIN,Super User,NaN,NaN,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10137203401,01/08/2026 - 31/10/2026,3M,Subscription Invoice,PREMIUM 09.24,3515600,beIN,beIN Quartar Installment,CNE Head office,NaN,NaN,NaN
86580,19156432,Invoice,INV_9130063,2026-08-01,12:05:24 AM,Posted,2026-08-01,31/10/2026,NaN,1522,SYSADMIN,Super User,NaN,NaN,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10730987533,01/08/2026 - 31/10/2026,3M,Subscription Invoice,PREMIUM 09.24,3611505,beIN,beIN Quartar Installment,CNE Head office,NaN,NaN,NaN
86581,19038286,Invoice,INV_9130065,2026-08-01,12:05:24 AM,Posted,2026-08-01,31/10/2026,NaN,1522,SYSADMIN,Super User,NaN,NaN,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10709212509,01/08/2026 - 31/10/2026,3M,Subscription Invoice,PREMIUM 09.24,3868252,beIN,beIN Quartar Installment,CNE Head office,NaN,NaN,NaN
86582,13400833,Invoice,INV_9130069,2026-08-01,12:05:25 AM,Posted,2026-08-01,31/10/2026,NaN,1522,SYSADMIN,Super User,NaN,NaN,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10719496852,01/08/2026 - 31/10/2026,3M,Subscription Invoice,PREMIUM 09.24,3868343,beIN,beIN Quartar Installment,CNE Head office,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
754017,16721522,Invoice,INV_9191151,2026-08-23,11:27:48 PM,Posted,2026-08-23,22/11/2026,NaN,2839,Mobile_App,Mobile_App,NaN,Bill posted against Subscription Charge,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10388384587,23/08/2026 - 22/11/2026,3M,Subscription Invoice,ULTIMATE 09.24,4352969,beIN,beIN Quartar Installment,CNE Head office,NaN,NaN,NaN
754018,19105743,Invoice,INV_9191164,2026-08-23,11:30:34 PM,Posted,2026-08-24,23/11/2026,NaN,1522,SYSADMIN,Super User,NaN,Bill posted against Renewal Charge,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10719375478,24/08/2026 - 23/11/2026,3M,Subscription Invoice,PREMIUM 09.24,3759181,beIN,beIN Quartar Installment,CNE Head office,NaN,NaN,NaN
754019,13936616,Invoice,INV_9191165,2026-08-23,11:30:35 PM,Posted,2026-08-24,23/11/2026,NaN,1522,SYSADMIN,Super User,NaN,Bill posted against Renewal Charge,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10709159056,24/08/2026 - 23/11/2026,3M,Subscription Invoice,PREMIUM 09.24,3742037,beIN,beIN Quartar Installment,CNE Head office,NaN,NaN,NaN
754020,17379191,Invoice,INV_9191169,2026-08-23,11:30:39 PM,Posted,2026-08-24,23/11/2026,NaN,1522,SYSADMIN,Super User,NaN,Bill posted against Renewal Charge,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10137639018,24/08/2026 - 23/11/2026,3M,Subscription Invoice,PREMIUM 09.24,3754672,beIN,beIN Quartar Installment,CNE Head office,NaN,NaN,NaN
754022,19183849,Invoice,INV_9191193,2026-08-23,11:38:30 PM,Posted,2026-08-23,22/11/2026,NaN,1522,CNE_WebSite,CNE_WebSite,NaN,Bill Posted against Subscription Charge,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,10732607329,23/08/2026 - 22/11/2026,3M,Subscription Invoice,PREMIUM 09.24,4069730,beIN,beIN Quartar Installment,CNE Head office,NaN,NaN,NaN

In [48]:
ft.loc[ft['Plan Name']=='Com-AFCON 2025']

Empty DataFrame
Columns: [Subscriber Nr, Doc Type, Ftnr, Created Date, Created Time, Doc Status, Period From, Period To, Bank Date, Amount, User Name, User Fullname, Payment Ref No, Event Description, Payment Batch No, Batch Approval No, Default Entity Type, Collecting Entity, Pay Mode, Jv Type, Book Number, Smartcard, Bill Period, Bill Cycle, Invoice Type, Plan Name, Contract Number, Channel Provider, Subscriber Type, Subscriber Entity, Last Four Digits Of Card, PAYMENT_FLAG, DS_PAYMENT_FLAG]
Index: []