In [ ]:
import pandas as pd
pd.set_option("display.max_columns",None)

In [79]:
swap = pd.read_csv(r"S:\1000s project\1000s for swap.csv",dtype='str', on_bad_lines='skip')
bein = pd.read_csv(r"S:\29.09.25\26757323_BEINDATANEWRPT.CSV",dtype='str')

In [80]:
bein_active = bein.loc[(bein['Status']=='Active')]
bein_active= bein_active[['Customer Number','Customer Type','Smart Card','Decoder','Item Description STB']]

In [81]:
bein_dec_sc = bein[['Smart Card','Decoder','Item Description STB']]

In [82]:
active = swap.loc[swap['Customer Number'].isin(bein_active['Customer Number'])]

In [89]:
result = active.merge(bein_dec_sc, on=['Decoder'],how='left').drop_duplicates(subset='Customer Number')

In [ ]:
result = result[['Customer Number','Customer Type','Item Description STB']]
result = result.rename({"Item Description STB":"status"},axis=1)
result.loc[result['status'].isna(),'status'] = 'Swapped'
result.loc[result['status']!='Swapped','status'] = 'Renewed'
result.to_csv("")

In [119]:
bein.loc[bein['Customer Number']=='14924230']

,Customer Number,Customer Type,Entity,Contract Number,Start Date,End Date,Plan,Status,Decoder,Item Description STB,Smart Card,Item Description SC,Next Billing Date,Billing Cycle,PPV Balance,Customer Balance,Outstanding Balance
2210629,14924230,beIN Bi Installment,Shoubra 1,1436535,23-02-2021,22-02-2022,beIN Sports,DIS,0319132739,beIN Decoder 1000s,10137468590,beIN Smartcard 1000s,23-02-2022,3M,0 Dr,.01 Cr,.01 CR
2210630,14924230,beIN Bi Installment,Shoubra 1,1105439,20-02-2020,19-02-2021,beIN Sports,DIS,0319132739,beIN Decoder 1000s,10137468590,beIN Smartcard 1000s,20-02-2021,3M,0 Dr,.01 Cr,.01 CR
2210631,14924230,beIN Bi Installment,Shoubra 1,3813520,28-09-2025,27-09-2026,PREMIUM 09.24,Active,0319132739,beIN Decoder 1000s,10137468590,beIN Smartcard 1000s,28-03-2026,6M,0 Dr,.01 Cr,.01 CR
2210632,14924230,beIN Bi Installment,Shoubra 1,234384,20-02-2019,19-02-2020,beIN Sports,DIS,0319132739,beIN Decoder 1000s,10137468590,beIN Smartcard 1000s,20-02-2020,3M,0 Dr,.01 Cr,.01 CR

In [118]:
result.loc[result['Customer Number']=='14924230']

   Customer Number             Customer Type   status
30        14924230  beIN Quartar Installment  Renewed

In [84]:
bein.loc[bein['Decoder']=='0302803138']

Empty DataFrame
Columns: [Customer Number, Customer Type, Entity, Contract Number, Start Date, End Date, Plan, Status, Decoder, Item Description STB, Smart Card, Item Description SC, Next Billing Date, Billing Cycle, PPV Balance, Customer Balance, Outstanding Balance]
Index: []

In [117]:
swap.loc[swap['Customer Number']=='14924230']

,Customer Number,Customer Type,End Date,Decoder,Smart Card
80851,14924230,beIN Quartar Installment,22/2/2022,0319132739,10137468590