In [7]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [4]:
df = pd.read_csv(r"S:\21.09.26\30951609_NEWCNEFINTRANSRPT.CSV", on_bad_lines='skip')
df.columns

C:\Users\mturky\AppData\Local\Temp\1\ipykernel_12196\3422738578.py:1: DtypeWarning: Columns (20,30) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"S:\21.09.26\30951609_NEWCNEFINTRANSRPT.CSV", on_bad_lines='skip')

Index(['Subscriber Nr', 'Doc Type', 'Ftnr', 'Created Date', 'Created Time',
       'Doc Status', 'Period From', 'Period To', 'Bank Date', 'Amount',
       'User Name', 'User Fullname', 'Payment Ref No', 'Event Description',
       'Payment Batch No', 'Batch Approval No', 'Default Entity Type',
       'Collecting Entity', 'Pay Mode', 'Jv Type', 'Book Number', 'Smartcard',
       'Bill Period', 'Bill Cycle', 'Invoice Type', 'Plan Name',
       'Contract Number', 'Channel Provider', 'Subscriber Type',
       'Subscriber Entity', 'Last Four Digits Of Card', 'PAYMENT_FLAG',
       'DS_PAYMENT_FLAG'],
      dtype='object')

In [16]:
df1= df.copy()
df1['Created Date'] = pd.to_datetime(df1['Created Date'],dayfirst=True)
df1

,Subscriber Nr,Doc Type,Ftnr,Created Date,Created Time,Doc Status,Period From,Period To,Bank Date,Amount,User Name,User Fullname,Payment Ref No,Event Description,Payment Batch No,Batch Approval No,Default Entity Type,Collecting Entity,Pay Mode,Jv Type,Book Number,Smartcard,Bill Period,Bill Cycle,Invoice Type,Plan Name,Contract Number,Channel Provider,Subscriber Type,Subscriber Entity,Last Four Digits Of Card,PAYMENT_FLAG,DS_PAYMENT_FLAG
0,18944192,Credit Note,CR_733879,2026-01-01,03:07:04 PM,Posted,NaN,NaN,NaN,535.0,EYASSIN,IHAB YASSIN,NaN,PERMIT FEES,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,1.056998e+10,NaN,NaN,NaN,NaN,NaN,beIN,Clubs,CNE Commercial Warehouse,NaN,NaN,NaN
1,19231171,Debit Note,DR_733876,2026-01-01,03:02:08 PM,Posted,NaN,NaN,NaN,100.0,OYAHYA,Omar Ahmed Yahya,NaN,PRG,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,1.073881e+10,NaN,NaN,NaN,NaN,NaN,beIN,CNE Subscriber,Mohandeseen Showroom,NaN,NaN,NaN
2,18942140,Debit Note,DR_733884,2026-01-01,03:51:07 PM,Posted,NaN,NaN,NaN,100.0,OYAHYA,Omar Ahmed Yahya,NaN,prg,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,1.073101e+10,NaN,NaN,NaN,NaN,NaN,beIN,BeIN sports CC,CNE Head office,NaN,NaN,NaN
3,18913402,Debit Note,DR_733885,2026-01-01,04:00:46 PM,Posted,NaN,NaN,NaN,170.0,MOKARAM,Mohamed Karam Mohamed Morad,NaN,AD C1,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,1.050916e+10,NaN,NaN,NaN,NaN,NaN,beIN,BeIN sports CC,CNE Head office,NaN,NaN,NaN
4,19065887,Debit Note,DR_733897,2026-01-01,04:40:48 PM,Posted,NaN,NaN,NaN,535.0,MMEGID,MAHMOUD ABD EL MEGID,NaN,PERMIT FEES,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,1.070917e+10,NaN,NaN,NaN,NaN,NaN,beIN,Clubs,beIN Commercial Warehouse,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
840589,19189586,Payment,PYMT_4117058,2026-09-20,10:12:56 PM,Posted,NaN,NaN,NaN,3045.0,CNE_WebSite,CNE_WebSite,1915657,9676674681,NaN,NaN,CNE Head Office,CNE Head office,Cash,NaN,NaN,1.073281e+10,NaN,NaN,NaN,NaN,NaN,beIN,CNE Subscriber,CNE Head office,NaN,Automation,No Flag
840590,19184408,Payment,PYMT_4117061,2026-09-20,10:31:10 PM,Posted,NaN,NaN,NaN,1522.0,FAWRY,FAWRY,1915660,1406958010,NaN,NaN,CNE Head Office,CNE Head office,Cash,NaN,NaN,1.073267e+10,NaN,NaN,NaN,NaN,NaN,beIN,beIN Quartar Installment,CNE Head office,NaN,Automation,No Flag
840591,19080677,Payment,PYMT_4117067,2026-09-20,10:44:02 PM,Posted,NaN,NaN,NaN,6087.0,Mobile_App,Mobile_App,1915664,538733871,NaN,NaN,CNE Head Office,CNE Head office,Cash,NaN,NaN,1.069714e+10,NaN,NaN,NaN,NaN,NaN,beIN,CNE Subscriber,CNE Head office,NaN,Automation,No Flag
840592,EDDMADI,Payment,PYMT_4117070,2026-09-20,10:57:18 PM,Posted,NaN,NaN,NaN,8700.0,ADHAMED,ABDALLAH DARWISH HAMED,NaN,AAIB Transfer Payment Date 20-09-2026,NaN,NaN,CNE Dealer,CNE Head office,CIB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Maadi,NaN,NaN,NaN
840593,18989133,Payment,PYMT_4117074,2026-09-20,11:08:44 PM,Posted,NaN,NaN,NaN,6087.0,Mobile_App,Mobile_App,1915669,538748406,NaN,NaN,CNE Head Office,CNE Head office,Cash,NaN,NaN,1.067963e+10,NaN,NaN,NaN,NaN,NaN,beIN,CNE Subscriber,CNE Head office,NaN,Automation,No Flag

In [12]:
df.loc[(df['Plan Name'].str.contains('2027',case=False,na=False)) & (df['Doc Status']=='Posted')]

,Subscriber Nr,Doc Type,Ftnr,Created Date,Created Time,Doc Status,Period From,Period To,Bank Date,Amount,User Name,User Fullname,Payment Ref No,Event Description,Payment Batch No,Batch Approval No,Default Entity Type,Collecting Entity,Pay Mode,Jv Type,Book Number,Smartcard,Bill Period,Bill Cycle,Invoice Type,Plan Name,Contract Number,Channel Provider,Subscriber Type,Subscriber Entity,Last Four Digits Of Card,PAYMENT_FLAG,DS_PAYMENT_FLAG
8103,17560917,Invoice,INV_8675139,27-01-2026 00:00:00,06:12:39 PM,Posted,02-01-2026 00:00:00,02-01-2026 00:00:00,NaN,4.26,ADHAMED,ABDALLAH DARWISH HAMED,NaN,NaN,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,1.038863e+10,02/01/2026 - 02/01/2026,15M,Subscription Invoice,SA AFC 2027,4030544.0,beIN,CNE Subscriber,CNE Head office,NaN,NaN,NaN
16837,19016170,Invoice,INV_8723115,22-02-2026 00:00:00,02:31:48 PM,Posted,22-02-2026 00:00:00,21-05-2027 00:00:00,NaN,1710.00,cneoctuser8,EDD OCTOBER user8,NaN,Bill posted against Subscription Charge,NaN,NaN,CNE Dealer,NaN,NaN,NaN,NaN,1.069116e+10,22/02/2026 - 21/05/2027,15M,Subscription Invoice,AddON AFC 2027,4069557.0,beIN,CNE Subscriber,October,NaN,NaN,NaN
19416,19233315,Invoice,INV_8740527,01-03-2026 00:00:00,02:33:28 PM,Posted,01-03-2026 00:00:00,31-05-2027 00:00:00,NaN,1710.00,cnenlcuser4,EDD NILE CENTER user4,NaN,Bill posted against Subscription Charge,NaN,NaN,CNE Dealer,NaN,NaN,NaN,NaN,1.073882e+10,01/03/2026 - 31/05/2027,15M,Subscription Invoice,AddON AFC 2027,4080494.0,beIN,CNE Subscriber,Domiat,NaN,NaN,NaN
21194,18913129,Invoice,INV_8754085,06-03-2026 00:00:00,11:08:32 PM,Posted,06-03-2026 00:00:00,05-06-2027 00:00:00,NaN,1710.00,Mobile_App,Mobile_App,NaN,Bill posted against Subscription Charge,NaN,NaN,CNE Head Office,NaN,NaN,NaN,NaN,1.065579e+10,06/03/2026 - 05/06/2027,15M,Subscription Invoice,AddON AFC 2027,4088745.0,beIN,CNE Subscriber,CNE Head office,NaN,NaN,NaN
21678,19185887,Invoice,INV_8757183,08-03-2026 00:00:00,11:24:53 AM,Posted,08-03-2026 00:00:00,07-06-2027 00:00:00,NaN,1710.00,cnealx5user2,EDD ALEX5 user2,NaN,Bill posted against Subscription Charge,NaN,NaN,CNE Dealer,NaN,NaN,NaN,NaN,1.073266e+10,08/03/2026 - 07/06/2027,15M,Subscription Invoice,AddON AFC 2027,4090493.0,beIN,CNE Subscriber,Alex 3,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
838764,17365094,Invoice,INV_9283991,15-09-2026 00:00:00,10:26:58 PM,Posted,15-09-2026 00:00:00,14-12-2027 00:00:00,NaN,1710.00,cneobruser4,EDD ELOUBOUR user4,NaN,Bill posted against Subscription Charge,NaN,NaN,CNE Dealer,NaN,NaN,NaN,NaN,1.013770e+10,15/09/2026 - 14/12/2027,15M,Subscription Invoice,AddON AFC 2027,4709049.0,beIN,CNE Subscriber,CNE Head office,NaN,NaN,NaN
839131,19166545,Invoice,INV_9284819,16-09-2026 00:00:00,01:08:47 PM,Posted,16-09-2026 00:00:00,15-12-2027 00:00:00,NaN,1710.00,mabdelmawla,mohamed abdelmawla,NaN,Bill posted against Subscription Charge,NaN,NaN,Partner Head Office,NaN,NaN,NaN,NaN,1.073270e+10,16/09/2026 - 15/12/2027,15M,Subscription Invoice,AddON AFC 2027,4709722.0,beIN,CNE Subscriber,CNE Head office,NaN,NaN,NaN
839140,19099216,Invoice,INV_9284930,16-09-2026 00:00:00,03:28:12 PM,Posted,16-09-2026 00:00:00,15-12-2027 00:00:00,NaN,1710.00,beinalxagent2,beIN Alex agent2,NaN,Bill posted against Subscription Charge,NaN,NaN,Bein Dealer,NaN,NaN,NaN,NaN,1.071956e+10,16/09/2026 - 15/12/2027,15M,Subscription Invoice,AddON AFC 2027,4709811.0,beIN,beIN Bi Installment,beIN Mahalla Dealer,NaN,NaN,NaN
839204,19079219,Invoice,INV_9285462,16-09-2026 00:00:00,09:43:20 PM,Posted,16-09-2026 00:00:00,15-12-2027 00:00:00,NaN,1710.00,beinaorabagent6,beIN Ahmed Orabey agent6,NaN,Bill posted against Subscription Charge,NaN,NaN,Bein Dealer,NaN,NaN,NaN,NaN,1.069739e+10,16/09/2026 - 15/12/2027,15M,Subscription Invoice,AddON AFC 2027,4710267.0,beIN,CNE Subscriber,beIN El Tayran,NaN,NaN,NaN
839862,19170719,Invoice,INV_9288488,19-09-2026 00:00:00,03:22:17 PM,Posted,19-09-2026 00:00:00,18-12-2027 00:00:00,NaN,1710.00,beintyrnagent1,beIN El Tayran agent1,NaN,Bill posted against Subscription Charge,NaN,NaN,Bein Dealer,NaN,NaN,NaN,NaN,1.073262e+10,19/09/2026 - 18/12/2027,15M,Subscription Invoice,AddON AFC 2027,4712444.0,beIN,CNE Subscriber,beIN El Tayran,NaN,NaN,NaN

In [ ]:
df["Swap Datetime"] = pd.to_datetime(
            df["Swap Date"].str.split().str[0] + " " + df["Swap Time"],
            dayfirst=True
        )

In [ ]:
19126641