In [139]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [140]:
pair = pd.read_excel(r"S:\01.09.25 Pairing.xlsx",dtype='str')
bein = pd.read_csv(r"S:\01.09.25\26418847_BEINDATANEWRPT.CSV",dtype=str)

In [157]:
pair_copy = pair.copy()
pair_copy['DECODER'] = pair_copy['MESSAGE'].str.split(",").str[-1]
pair_copy['CREATED_DATE'] = pd.to_datetime(pair_copy['CREATED_DATE'])
na_filter = pair_copy['CUSTOMER_NUMBER'].isna()
sysadmin_filter = pair_copy['CREATED_BY_NAME']=='Super User'
invalid_filter = pair_copy['STATUS_NAME']=='Invalid'

pair_copy = pair_copy.loc[(~(na_filter & sysadmin_filter))]
pair_copy = pair_copy.loc[~(invalid_filter)]

pair_copy= pair_copy.sort_values(['CUSTOMER_NUMBER',"CREATED_DATE"],ascending=[True,False])
pair_copy = pair_copy.drop_duplicates(subset=['CUSTOMER_NUMBER'], keep="first")

In [158]:
bein_copy = bein.copy()
active_filter = bein['Status']=='Active'
bein_copy=bein_copy.loc[active_filter]
bein_copy['Original Decoder'] = bein_copy['Decoder']
bein_copy['Decoder'] = bein_copy['Decoder'].str[1:]
bein_copy['Original Smart Card'] = bein_copy['Smart Card']

bein_copy['Smart Card'] = bein_copy['Smart Card'].str[:-1]
bein_copy = bein_copy.loc[:,['Customer Number','Original Smart Card','Smart Card','Original Decoder','Decoder']]
bein_copy = bein_copy.drop_duplicates()

In [159]:
merged_dec = pd.merge(left=bein_copy,right=pair_copy, left_on='Decoder', right_on='DECODER', how='right')
merged_dec = merged_dec.loc[merged_dec['SMART_CARD']!=merged_dec['Smart Card']].drop_duplicates()
merged_dec = merged_dec.loc[~merged_dec['Decoder'].isna()]
# merged_dec = merged_dec.drop_duplicates()

In [160]:
merged_sc = pd.merge(left=bein_copy,right=pair_copy, left_on='Smart Card', right_on='SMART_CARD', how='right')
merged_sc = merged_sc.loc[merged_sc['DECODER']!=merged_sc['Decoder']].drop_duplicates()
merged_sc = merged_sc.loc[~merged_sc['Decoder'].isna()]
# merged_sc = merged_sc.drop_duplicates()

In [166]:
display(merged_sc)
merged_sc.to_csv("wrong pair same sc different dec.csv",index=False)

,Customer Number,Original Smart Card,Smart Card,Original Decoder,Decoder,REQUEST_ID,CREATED_DATE,STATUS_NAME,CUSTOMER_NUMBER,CREATED_BY_NAME,SMART_CARD,LAST_UPD_DATE,MESSAGE,DECODER
872,12235102,42768285167,4276828516,0320087696,320087696,36367322,2025-08-03 22:45:26,Accept,12235102,EDD ALEX2 user1,4276828516,2025-08-03 22:45:30,"SCPAIR,CNE002,4276828516,302738272",302738272
1360,12642068,10697285822,1069728582,0370408270,370408270,34888306,2025-01-03 19:18:22,Accept,12642068,Nour Ehab Helmy,1069728582,2025-01-03 19:18:27,"SCPAIR,CNE002,1069728582,370385246",370385246
2692,13567455,10708868798,1070886879,0302812212,302812212,35368712,2025-03-04 22:41:09,Accept,13567455,EDD ZAHRAA ELMAADI user5,1070886879,2025-03-04 22:41:17,"SCPAIR,CNE002,1070886879,351918750",351918750
2897,13684494,10731066261,1073106626,0296501871,296501871,35040251,2025-01-26 12:29:38,Accept,13684494,EDD ZAHRAA ELMAADI user3,1073106626,2025-01-26 12:29:43,"SCPAIR,CNE002,1073106626,373035362",373035362
3045,13716050,10691009764,1069100976,0302802564,302802564,36380107,2025-08-05 14:50:08,Accept,13716050,EDD SUEZ user1,1069100976,2025-08-05 14:51:08,"SCPAIR,CNE002,1069100976,363329902",363329902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
102696,19192265,10732877989,1073287798,0360942944,360942944,35681088,2025-04-10 12:55:39,Accept,19192265,IHAB YASSIN,1073287798,2025-04-10 12:56:06,"SCPAIR,CNE002,1073287798,373083960",373083960
107119,19198164,10732606636,1073260663,0360933158,360933158,36075235,2025-06-03 19:10:21,Accept,19197226,EDD MEET GHAMR user2,1073260663,2025-06-03 19:10:26,"SCPAIR,CNE002,1073260663,373065258",373065258
107929,19198194,10732655039,1073265503,0363274205,363274205,36302859,2025-07-21 15:15:16,Accept,19198194,Omar Ahmed Yahya,1073265503,2025-07-21 15:15:23,"SCPAIR,CNE002,1073265503,373022212",373022212
108059,19198352,10732853162,1073285316,0363372555,363372555,36334114,2025-07-29 12:05:51,Accept,19198352,AHMED FARAAG,1073285316,2025-07-29 12:06:07,"SCPAIR,CNE002,1073285316,370389700",370389700
110740,7164112,10088528202,1008852820,0303449017,303449017,34900118,2025-01-04 19:01:56,Accept,7164112,Mostafa Mohamed Abd Al Monaim,1008852820,2025-01-04 19:02:06,"SCPAIR,CNE002,1008852820,303449475",303449475

In [167]:
display(merged_dec)
merged_dec.to_csv("wrong pair same dec different sc.csv",index=False)

,Customer Number,Original Smart Card,Smart Card,Original Decoder,Decoder,REQUEST_ID,CREATED_DATE,STATUS_NAME,CUSTOMER_NUMBER,CREATED_BY_NAME,SMART_CARD,LAST_UPD_DATE,MESSAGE,DECODER
13715,14360605,10088548747,1008854874,0315105909,315105909,35779224,2025-04-25 17:02:05,Accept,15131446,EDD Omrania user1,1013756659,2025-04-25 17:02:07,"SCPAIR,CNE002,1013756659,315105909",315105909
15612,15401671,10137282397,1013728239,0315072533,315072533,35865045,2025-05-06 15:21:50,Accept,15401671,Techuser1,1013722738,2025-05-06 15:22:06,"SCPAIR,CNE002,1013722738,315072533",315072533
34562,19194215,10732778070,1073277807,0373028743,373028743,35678998,2025-04-10 00:34:42,Accept,17985926,Shehab Said Ahmed Said,1059011063,NaN,"SCPAIR,CNE002,1059011063,373028743",373028743
37086,18278797,10570242882,1057024288,0315534870,315534870,35983046,2025-05-20 21:06:24,Accept,18278797,Mahmoud gamal,1056987618,2025-05-20 21:06:26,"SCPAIR,CNE002,1056987618,315534870",315534870
45041,19199682,10732866388,1073286638,0373069861,373069861,36602865,2025-08-20 20:28:17,Accept,18915165,Ahmed Moustafa Khalil,1065578749,NaN,"SCPAIR,CNE002,1065578749,373069861",373069861
52496,18975944,10731045711,1073104571,0351825533,351825533,36476118,2025-08-13 21:42:32,Accept,18975944,Mohamed Sayed AbdelAziz,1067982385,2025-08-13 21:43:09,"SCPAIR,CNE002,1067982385,351825533",351825533
74243,19186152,10732631964,1073263196,0373053609,373053609,35411342,2025-03-10 04:07:26,Accept,19106831,Shehab Said Ahmed Said,1071955346,NaN,"SCPAIR,CNE002,1071955346,373053609",373053609
78418,19125869,10088560106,1008856010,0319186321,319186321,36090683,2025-06-06 11:44:03,Accept,19125869,Marwa Mostafa,4291667407,NaN,"SCPAIR,CNE002,4291667407,319186321",319186321
87178,19196407,10732776942,1073277694,0373029884,373029884,35875883,2025-05-07 08:12:23,Accept,19158719,May Hosny Mohamed,1073098509,NaN,"SCPAIR,CNE002,1073098509,373029884",373029884
97009,19182496,10732653661,1073265366,0370405582,370405582,36677661,2025-08-27 21:09:13,Accept,19185691,beIN Mahalla user 1,1073087527,2025-08-27 21:10:10,"SCPAIR,CNE002,1073087527,370405582",370405582
110740,7164112,10088528210,1008852821,0303449475,303449475,34900118,2025-01-04 19:01:56,Accept,7164112,Mostafa Mohamed Abd Al Monaim,1008852820,2025-01-04 19:02:06,"SCPAIR,CNE002,1008852820,303449475",303449475

In [163]:
pair.loc[pair['CUSTOMER_NUMBER']=='10099993']

,REQUEST_ID,CREATED_DATE,STATUS_NAME,CUSTOMER_NUMBER,CREATED_BY_NAME,SMART_CARD,LAST_UPD_DATE,MESSAGE
18702,36590067,2025-08-19 15:10:32,Accept,10099993,Ayman Mahmoud,4278893401,NaN,"SCPAIR,CNE002,4278893401,363277515"
18704,36590060,2025-08-19 15:09:23,Accept,10099993,Ayman Mahmoud,4278893401,2025-08-19 15:10:10,"SCPAIR,CNE002,4278893401,319669287"
88374,35998019,2025-05-22 21:10:45,Accept,10099993,Techuser1,4278893401,2025-05-22 21:24:51,"SCPAIR,CNE002,4278893401,319669287"
258660,34879325,2025-01-02 18:28:58,Accept,10099993,Mohamed Nassef Emam Helal,4278893401,2025-01-02 18:29:07,"SCPAIR,CNE002,4278893401,319669287"
259934,34858804,2025-01-01 00:55:06,Accept,10099993,Super User,4278893401,2025-01-01 00:55:12,"SCPAIR,CNE002,4278893401,319669287"

In [164]:


bein_copy.loc[bein_copy['Customer Number']=="10099993"]

,Customer Number,Original Smart Card,Smart Card,Original Decoder,Decoder
2730811,10099993,42788934018,4278893401,0363277515,363277515