In [28]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [29]:
all = pd.read_csv(r"C:\Users\mturky\Downloads\26746385_ALLUSERHISTDTLS\26746385_ALLUSERHISTDTLS.CSV",dtype='str')
modify = pd.read_csv(r"C:\Users\mturky\Downloads\26746386_MODIFYSUBSTYPERPT.CSV",dtype='str')

In [30]:
filter_sharaf = modify['User Code'].str.lower().str.contains('sharaf')
filter_cne = modify['User Code'].str.lower().str.contains('cne')
filter_edd = modify['User Code'].str.lower().str.contains('edd')
filter_dis = modify['User Code'].str.lower().str.contains('dis')
filter_bein = modify['User Code'].str.lower().str.contains('bein')

In [31]:
all_copy = all.loc[all['Transaction Type']=="Post Paid"].copy()
modify_copy = modify.loc[filter_cne | filter_edd | filter_dis | filter_sharaf | filter_bein].copy()

In [32]:
all_copy["Transaction Date"] = pd.to_datetime(all_copy["Transaction Date"],dayfirst=True)
modify_copy['Modified Date'] = pd.to_datetime(modify_copy['Modified Date'],dayfirst=True)
all_copy['Transaction Date'] = pd.to_datetime(all_copy['Transaction Date'].dt.date, dayfirst=True)

C:\Users\mturky\AppData\Local\Temp\1\ipykernel_24624\609106723.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  all_copy["Transaction Date"] = pd.to_datetime(all_copy["Transaction Date"],dayfirst=True)
C:\Users\mturky\AppData\Local\Temp\1\ipykernel_24624\609106723.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  modify_copy['Modified Date'] = pd.to_datetime(modify_copy['Modified Date'],dayfirst=True)

In [33]:
merged = pd.merge(left=modify_copy,right=all_copy,left_on=['Customer Number','Modified Date'] , right_on=['Customer#','Transaction Date'], how="left")

In [34]:
result = merged.loc[merged['Customer#'].isna()]
result = result.drop_duplicates(subset='Customer Number')

In [38]:
result.to_csv("sheikh result.csv", index=False)

In [36]:
display(all.loc[all['Customer#']=='19190771'])
display(modify.loc[modify['Customer Number']=='19190771'])

,Customer#,Outstanding Balance,User Entity,Transaction Type,Transaction#,Transaction User,Transaction Date,Description,PPV Balance,Account Balance,Total Balance
3309,19190771,0 DR,beIN Kafr el sheikh,Modify Customer,19190771,beIN Kafr el sheikh user 1,26-09-2025 07:34:39 PM,Customer with # 19190771 has been modified,0 Dr,0 Dr,0 Dr
9801,19190771,0 DR,CNE Head office,Disconnect Contract,28737393,Super User,26-09-2025 02:07:07 AM,Provisioning request has been confirmed for th...,0 Dr,0 Dr,0 Dr
9890,19190771,0 DR,CNE Head office,Disconnect Contract,28737393,Super User,26-09-2025 02:06:22 AM,Provisioning request has been generated for th...,0 Dr,0 Dr,0 Dr
13693,19190771,0 DR,CNE Head office,Disconnect Contract,28737393,Super User,26-09-2025 02:01:14 AM,Provisioning setup has done for the Order # 61...,0 Dr,0 Dr,0 Dr
13694,19190771,0 DR,CNE Head office,Disconnect Contract,3570921,Super User,26-09-2025 02:01:14 AM,Contract # 3570921 with Plan(s) PREMIUM6mEss F...,0 Dr,0 Dr,0 Dr
13698,19190771,0 DR,CNE Head office,Modify Connection,902803,Super User,26-09-2025 02:01:14 AM,Connection# 902803 Modified successfully,0 Dr,0 Dr,0 Dr

,Customer Number,Old Customer Type,New Customer Type,Modified Date,Modified Time,User Code,User Name
1963,19190771,CNE Subscriber,beIN Quartar Installment,26/09/2025 12:00:00 AM,19:34:39,beinkafruser1,beIN Kafr el sheikh user 1